### ISSUE TITLE
[i18n-zh] Translating docs to Chinese

### ISSUE THREAD

**Issue by Ayuilos** [huggingface/smolagents#141]
Hello Huggingface team, I've checked "smolagents" recently, and I'm interested in it, I would like to help translate docs.😀

I'll be responsible to chapters below in next 2 weeks.

```yml
- title: Get started
  sections:
  - local: index
    title: 🤗 Agents
  - local: guided_tour
    title: Guided tour
- title: Tutorials
  sections:
  - local: tutorials/building_good_agents
    title: ✨ Building good agents
  - local: tutorials/tools
    title: 🛠️ Tools - in-depth guide
  - local: tutorials/secure_code_execution
    title: 🛡️ Secure your code execution with E2B
- title: Conceptual guides
  sections:
  - local: conceptual_guides/intro_agents
    title: 🤖 An introduction to agentic systems
  - local: conceptual_guides/react
    title: 🤔 How do Multi-step agents work?
```

I also found [reply](https://github.com/huggingface/smolagents/issues/80#issuecomment-2581382181) from @aymeric-roucher under https://github.com/huggingface/smolagents/issues/80, I could also add this video to the "Guided tour" of `zh` translation docs.
